### Understand Autograd

In [2]:
# 1. use numpy to finish a computation
import numpy as np

np.random.seed(0)

N, D = 3, 4

x = np.random.randn(N, D) # standard normal distribution
y = np.random.randn(N, D)
z = np.random.randn(N, D)

# c = (x*y+z)*1
a = x * y
b = a + z
c = np.sum(b)

In [3]:
# 2. use tensor to finish a computation
import torch as t

tx = t.from_numpy(x)
# or you can use t.randn(N, D, requires_grad=True) to create tensor
ty = t.from_numpy(y)
tz = t.from_numpy(z)

tx.requires_grad = True # if false then cannot calculate gradient

ta = tx * ty
tb = ta + tz
tc = t.sum(tb)

tc.item() # get value from scalar object

6.7170085378000675

In [4]:
# 3. use numpy to calculate gradient
grad_c = 1.0
grad_b = grad_c * np.ones((N, D))
grad_a = grad_b.copy()
grad_z = grad_b.copy()
grad_x = grad_a * y
grad_y = grad_a * x

print(grad_x)

[[ 0.76103773  0.12167502  0.44386323  0.33367433]
 [ 1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502]]


In [5]:
# 4. use autograd in pytorch to calculate gradient
tc.backward()
print(tx.grad)
print(ty.grad) # none because yt.requires_grad = False

tensor([[ 0.7610,  0.1217,  0.4439,  0.3337],
        [ 1.4941, -0.2052,  0.3131, -0.8541],
        [-2.5530,  0.6536,  0.8644, -0.7422]], dtype=torch.float64)
None


In [6]:
# 5. about tensor
t1 = t.tensor(3.0, requires_grad = True)

print(t1.requires_grad)
print(t1.data)
print(t1.shape)
print(t1.device)
print(t1.grad_fn)
print(t1.tolist())

True
tensor(3.)
torch.Size([])
cpu
None
3.0


In [10]:
tx

tensor([[ 1.7641,  0.4002,  0.9787,  2.2409],
        [ 1.8676, -0.9773,  0.9501, -0.1514],
        [-0.1032,  0.4106,  0.1440,  1.4543]], dtype=torch.float64,
       requires_grad=True)

In [11]:
tx[None]

tensor([[[ 1.7641,  0.4002,  0.9787,  2.2409],
         [ 1.8676, -0.9773,  0.9501, -0.1514],
         [-0.1032,  0.4106,  0.1440,  1.4543]]], dtype=torch.float64,
       grad_fn=<UnsqueezeBackward0>)

In [18]:
img_t = t.ones(3, 5, 5)

In [29]:
img_t.sum(-2)

tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])

In [30]:
weights = t.tensor([0.2, 0.7, 0.1])

In [37]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [40]:
unsqueezed_weights.shape, img_t.shape

(torch.Size([3, 1, 1]), torch.Size([3, 5, 5]))

In [44]:
img_t* unsqueezed_weights

tensor([[[0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000],
         [0.2000, 0.2000, 0.2000, 0.2000, 0.2000]],

        [[0.7000, 0.7000, 0.7000, 0.7000, 0.7000],
         [0.7000, 0.7000, 0.7000, 0.7000, 0.7000],
         [0.7000, 0.7000, 0.7000, 0.7000, 0.7000],
         [0.7000, 0.7000, 0.7000, 0.7000, 0.7000],
         [0.7000, 0.7000, 0.7000, 0.7000, 0.7000]],

        [[0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000],
         [0.1000, 0.1000, 0.1000, 0.1000, 0.1000]]])